# Etapa 1: Build
FROM rust:1.85 as builder

WORKDIR /app

# Instalar dependencias para compilar
RUN apt-get update && apt-get install -y libpq-dev pkg-config libssl-dev

# Instalar sqlx-cli
RUN cargo install sqlx-cli --no-default-features --features postgres

# Copiar archivos necesarios
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations

# Compilar binario de la app
RUN cargo build --release --locked

# Etapa 2: Runtime
FROM debian:bookworm-slim

# Instalar solo runtime deps
RUN apt-get update && apt-get install -y libpq5 postgresql-client ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiar binario compilado
COPY --from=builder /app/target/release/tdl-api .
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx
COPY --from=builder /app/migrations ./migrations
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

EXPOSE 8080

CMD ["./entrypoint.sh"]
