services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: tdl-api:latest
    container_name: rust_api
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data:
